apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: hpzm5s377-python 
  janus-idp.io/tekton: hpzm5s377-python
  backstage.io/kubernetes-id: hpzm5s377-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hpzm5s377-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  