apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: hpzm5s377-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hpzm5s377-python 
  name: hpzm5s377-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: hpzm5s377-python 
